Main = (->

  init = () ->
    $('#slider').slick
      speed: 200,
      autoplay: true,
      autoplaySpeed: 6000

    $(document).on 'click', '.scroll-cta', ->
      console.log 'scroll'

    drawChart()



  drawChart = () ->
    Chart.defaults.global =
      animation: true
      animationSteps: 60
      animationEasing: 'easeOutQuart'
      showScale: true
      scaleOverride: false
      scaleSteps: null
      scaleStepWidth: null
      scaleStartValue: null
      scaleLineColor: 'rgba(0,0,0,.1)'
      scaleLineWidth: 1
      scaleShowLabels: false
      scaleLabel: '<%=value%>'
      scaleIntegersOnly: true
      scaleBeginAtZero: false
      scaleFontFamily: '\'Helvetica Neue\', \'Helvetica\', \'Arial\', sans-serif'
      scaleFontSize: 12
      scaleFontStyle: 'normal'
      scaleFontColor: '#666'
      responsive: true
      maintainAspectRatio: false
      showTooltips: true
      customTooltips: false
      tooltipEvents: [
        'mousemove'
        'touchstart'
        'touchmove'
      ]
      tooltipFillColor: 'rgba(0,0,0,0.8)'
      tooltipFontFamily: '\'Helvetica Neue\', \'Helvetica\', \'Arial\', sans-serif'
      tooltipFontSize: 14
      tooltipFontStyle: 'normal'
      tooltipFontColor: '#fff'
      tooltipTitleFontFamily: '\'Helvetica Neue\', \'Helvetica\', \'Arial\', sans-serif'
      tooltipTitleFontSize: 14
      tooltipTitleFontStyle: 'bold'
      tooltipTitleFontColor: '#fff'
      tooltipYPadding: 6
      tooltipXPadding: 6
      tooltipCaretSize: 8
      tooltipCornerRadius: 6
      tooltipXOffset: 10
      tooltipTemplate: '<%if (label){%><%=label%>: <%}%><%= value %>'
      multiTooltipTemplate: '<%= value %>'
      onAnimationProgress: ->
      onAnimationComplete: ->


    randomScalingFactor = ->
      Math.round Math.random() * 10

    lineChartData =
      labels: [
        'Jan'
        'Feb'
        'Mar'
        'Apr'
        'May'
        'Jun'
        'Jul'
        'Aug'
        'Sep'
        'Oct'
        'Nov'
        'Dec'
      ]
      datasets: [
        {
          label: 'My First dataset'
          fillColor: 'rgba(220,220,220,0.2)'
          strokeColor: 'rgba(220,220,220,1)'
          pointColor: 'rgba(220,220,220,1)'
          pointStrokeColor: '#fff'
          pointHighlightFill: '#fff'
          pointHighlightStroke: 'rgba(220,220,220,1)'
          data: [
            randomScalingFactor()
            randomScalingFactor()
            randomScalingFactor()
            randomScalingFactor()
            randomScalingFactor()
            randomScalingFactor()
            randomScalingFactor()
            randomScalingFactor()
            randomScalingFactor()
            randomScalingFactor()
            randomScalingFactor()
            randomScalingFactor()
          ]
        }
      ]

    window.onload = ->
      ctx = document.getElementById('canvas').getContext('2d')
      window.myLine = new Chart(ctx).Line(lineChartData, {bezierCurve: false, scaleShowHorizontalLines: false, pointDotRadius : 7})
      return

    # ---
    # generated by js2coffee 2.2.0

  return {
    init: init
  }
)()
