Main = (->

  init = () ->
    $('#slider').slick
      speed: 200,
      autoplay: true,
      autoplaySpeed: 6000

    $(document).on 'click', '.corner', ->
      $(this).parents('.flip-container').addClass('flipped')

    $(document).on 'click', '.card .close', ->
      $(this).parents('.flip-container').removeClass('flipped')

    $(document).on 'click', '.scroll', ->
      $('html, body').animate { scrollTop: $('#license').offset().top }, 450

    drawChart()
    createDragger()

  createDragger = () ->
    new Dragdealer('just-a-slider', {
      x: 0.5,
      animationCallback: (x, y) ->
        $('.graph-inner').css('left', (x * 100) + "%")
    }) 
  drawChart = () ->

    Chart.defaults.global =
      animation: true
      animationSteps: 60
      animationEasing: 'easeOutQuart'
      showScale: true
      scaleOverride: false
      scaleSteps: null
      scaleStepWidth: null
      scaleStartValue: null
      scaleLineColor: 'rgba(1,1,1,0)'
      scaleLineWidth: 1
      scaleShowLabels: false
      scaleLabel: '<%=value%>'
      scaleIntegersOnly: true
      scaleBeginAtZero: false
      scaleFontFamily: '\'Helvetica Neue\', \'Helvetica\', \'Arial\', sans-serif'
      scaleFontSize: 12
      scaleFontStyle: 'normal'
      scaleFontColor: '#666'
      responsive: true
      maintainAspectRatio: false
      showTooltips: true
      customTooltips: false
      tooltipEvents: [
        'mousemove'
        'touchstart'
        'touchmove'
      ]
      tooltipFillColor: 'rgba(83,187,179,1)'
      tooltipFontFamily: '\'Helvetica Neue\', \'Helvetica\', \'Arial\', sans-serif'
      tooltipFontSize: 14
      tooltipFontStyle: 'normal'
      tooltipFontColor: '#fff'
      tooltipTitleFontFamily: '\'Roboto\', \'Helvetica Neue\', \'Helvetica\', \'Arial\', sans-serif'
      tooltipTitleFontSize: 14
      tooltipTitleFontStyle: 'normal'
      tooltipTitleFontColor: '#fff'
      tooltipYPadding: 15
      tooltipXPadding: 20
      tooltipCaretSize: 8
      tooltipCornerRadius: 20
      tooltipXOffset: 50
      tooltipYOffset: 50
      tooltipTemplate: '<%if (label){%><%=label%>: $<%}%><%= value %>'
      multiTooltipTemplate: '<%= value %>'
      onAnimationProgress: ->
      onAnimationComplete: ->


    randomScalingFactor = ->
      Math.round Math.random() * (5000 - 100) + 100;

    lineChartData =
      labels: [
        'Jan'
        'Feb'
        'Mar'
        'Apr'
        'May'
        'Jun'
        'Jul'
        'Aug'
        'Sep'
        'Oct'
        'Nov'
        'Dec'
      ]
      datasets: [
        {
          label: 'My First dataset'
          fillColor: 'rgba(250,250,250,0.6)'
          strokeColor: '#e1e8ee'
          pointColor: '#e1e8ee'
          pointStrokeColor: '#fff'
          pointHighlightFill: '#acbbba'
          pointHighlightStroke: '#acbbba'
          data: [
            randomScalingFactor()
            randomScalingFactor()
            randomScalingFactor()
            randomScalingFactor()
            randomScalingFactor()
            randomScalingFactor()
            randomScalingFactor()
            randomScalingFactor()
            randomScalingFactor()
            randomScalingFactor()
            randomScalingFactor()
            randomScalingFactor()
          ]
        }
      ]
       

    window.onload = ->
      ctx = document.getElementById('canvas').getContext('2d')
      window.myLine = new Chart(ctx).Line(lineChartData, {
        bezierCurve: false, 
        scaleGridLineColor: '#e1e8ee', 
        scaleShowHorizontalLines: false, 
        pointDotRadius : 7
      })
      return

    # ---
    # generated by js2coffee 2.2.0

  return {
    init: init
  }
)()
